name: Comment on PR
on: 
  pull_request:
    types:
      - opened
jobs:
  comment:
    if: ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        allow-repeats: false
        with:
        	message: |
            \#\# How to test manually 
            - [ ]  _happy path_
            - [ ]  _non-obvious corner cases_
            - [ ]  _potentialy affected areas_
            <details>
            <summary>Platforms checked</summary>
            - [ ] macOS
            - [ ] Windows
            - [ ] Android
            - [ ] iOS
            </details>
            \#\# [Automated tests](https://www.notion.so/pitch/How-to-write-tests-8dc88e45a0a34f37be958388a5acf2fe#124767a5ff6b4c2d8b2c6c016631bb91)
            - [ ] Created/modified
            - [ ] Separate ticket for tests is created  \#1234567