name: Comment on PR
on: 
  pull_request:
    types:
      - opened
jobs:
  comment:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ** How to test manually **